name: Executing Shell script

on: push

jobs:
    genrate_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        
        - name: Read File and List files
          run: |
            ls -latr

        - name: Execute Shell Script 
          run: |
            chmod +x ./ascii.sh
            ./ascii.sh
            
        - name: Read File and List files Again
          run: |
            ls -latr

