name: First workflow

on: push

jobs:
    First_Job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Check Ubuntu Version
          run: | 
            cat /etc/os-release
            run: echo "Welcome to GitHub Actions"
            run: ls -latr
        
        - name: Generate ASCII message
          run: cowsay -f dragon "Run, I'm DragonHeart" > dragon.txt
