name: Generate ASCII artwork

on: push

jobs:
    genrate_ascii:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install ascii package
          run: | 
            sudo apt-get install cowsay -y
        
        - name: Generate ASCII message
          run: cowsay -f dragon "Run, I'm DragonHeart" > dragon.txt

        - name: Test if file exist
          run: |
            FILE=dragon.txt
            if [ -f "$FILE" ]; then
                echo "$FILE exists."
            else 
                echo "$FILE does not exist."
            fi
        
        - name: Read Dragon File and List files
          run: |
            cat dragon.txt
            ls -latr

