name: Run Multi Jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install ascii package
          run: | 
            sudo apt-get install cowsay -y
        
        - name: Generate ASCII message
          run: cowsay -f dog "Run, I'm DogHeart" > dog.txt

        - name: Upload the Dog Artifact for other jobs
          uses: actions/upload-artifact@v4
          with:
             name: dog-file
             path: dog.txt
    
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dog Artifact for other jobs
          uses: actions/download-artifact@v4
          with:
            name: dog-file

        - name: Test File
          run: |
            ls -la
            grep -i "DogHeart" dog.txt

        - name: Test if dog file exist
          run: |
            FILE=dog.txt
            if [ -f "$FILE" ]; then
                echo "$FILE exists."
            else 
                echo "$FILE does not exist."
            fi
    
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dog Artifact for other jobs
          uses: actions/download-artifact@v4
          with:
            name: dradoggon-file

        - name: Deploying Job
          run: echo "Deploying ..." 

        - name: Read Dog File and List files
          run: |
            cat dog.txt
            ls -latr

