name: Run Multi Jobs

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Install ascii package
          run: | 
            sudo apt-get install cowsay -y
        
        - name: Generate ASCII message
          run: cowsay -f dragon "Run, I'm DragonHeart" > dragon.txt

        - name: Upload the Dragon Artifact for other jobs
          uses: actions/upload-artifact@v3
          with:
             name: dragon-file
             path: dragon.txt
    
    test_job_2:
        needs: build_job_1
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dragon Artifact for other jobs
          uses: actions/download-artifact@v3
          with:
            name: dragon-file
            path: dragon.txt

        - name: Test if dragon file exist
          run: |
            FILE=dragon.txt
            if [ -f "$FILE" ]; then
                echo "$FILE exists."
            else 
                echo "$FILE does not exist."
            fi
    
    deploy_job_3:
        needs: test_job_2
        runs-on: ubuntu-latest
        steps:
        - name: Download the Dragon Artifact for other jobs
          uses: actions/download-artifact@v3
          with:
            name: dragon-file

        - name: Deploying Job
          run: echo "Deploying ..." 

        - name: Read Dragon File and List files
          run: |
            cat dragon.txt
            ls -latr

